# Generated by Django 5.0.1 on 2026-07-07 03:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_Account', message='Account must be Alphanumeric', regex='^[a-zA-Z0-9]*$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_account', models.ForeignKey(db_column='user_account', on_delete=django.db.models.deletion.CASCADE, to='basic_info.person')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
