# Generated by Django 5.0.1 on 2026-06-29 01:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_Account', message='Account must be Alphanumeric', regex='^[a-zA-Z0-9]*$')])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('contentKeyWord', models.CharField(max_length=200)),
                ('userAccount', models.ForeignKey(db_column='userAccount', on_delete=django.db.models.deletion.CASCADE, to='basic_info.person', to_field='account')),
            ],
        ),
    ]
