# Generated by Django 5.0.1 on 2026-06-22 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0003_alter_person_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='uid',
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_info.person'),
        ),
    ]
