# Generated by Django 5.0.1 on 2026-06-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0004_remove_message_uid_remove_person_uid_message_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='userId',
        ),
    ]
