# Generated by Django 5.0.1 on 2026-06-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0005_rename_user_id_message_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
