# Generated by Django 5.2 on 2026-09-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestNews',
        ),
    ]
