# Generated by Django 5.0.1 on 2026-07-07 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, unique=True)),
                ('stock_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'hot_stock',
            },
        ),
        migrations.CreateModel(
            name='FavoriteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=100, unique=True)),
                ('user_account', models.ForeignKey(db_column='user_account', on_delete=django.db.models.deletion.CASCADE, to='basic_info.person')),
            ],
            options={
                'db_table': 'favorite_stock',
            },
        ),
    ]
