# Generated by Django 5.0.1 on 2026-06-29 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockCode', models.CharField(max_length=100, unique=True)),
                ('stockName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.ForeignKey(db_column='userAccount', on_delete=django.db.models.deletion.CASCADE, to='basic_info.person', to_field='account')),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.hotstock')),
            ],
        ),
    ]
