# Generated by Django 5.0.1 on 2026-06-22 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_info', '0005_rename_user_id_message_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=100, unique=True)),
                ('stock_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_info.person')),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.hotstock')),
            ],
        ),
    ]
