# Generated by Django 5.0.1 on 2026-07-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritestock',
            name='stockId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
