# Generated by Django 5.0.1 on 2026-07-08 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritestock',
            name='user_account',
            field=models.ForeignKey(db_column='user_account', db_comment='對應Person id', on_delete=django.db.models.deletion.CASCADE, to='basic_info.person'),
        ),
    ]
