# Generated by Django 5.0.1 on 2026-06-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotstock',
            old_name='stock_code',
            new_name='stockCode',
        ),
        migrations.RenameField(
            model_name='hotstock',
            old_name='stock_name',
            new_name='stockName',
        ),
    ]
