# Generated by Django 5.0.1 on 2026-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_favoritestock_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotstock',
            name='suffix',
            field=models.CharField(db_comment='.TW 或 .TWO', default='TW', max_length=50),
        ),
    ]
