# Generated by Django 5.0.1 on 2026-07-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_favoritestock_stockid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotstock',
            old_name='stockCode',
            new_name='stockId',
        ),
    ]
