# Generated by Django 5.0.1 on 2026-08-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
        ('stock', '0003_hotstock_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritestock',
            name='stock_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='favoritestock',
            constraint=models.UniqueConstraint(fields=('user_account', 'stock_id'), name='unique_person_stock'),
        ),
    ]
