# Generated by Django 5.0.1 on 2026-07-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_stockcode_hotstock_stockid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritestock',
            old_name='userId',
            new_name='userAccount',
        ),
    ]
